---
- stat: path=/etc/profile.d/cis_profile.sh
  register: cis_profile_stat
  tags:
    - baseline
    - tmout

- name: Update TMOUT template if this machine was configured for it to begin with
  ansible.builtin.template:
    src: templates/cis_profile.sh.j2
    dest: /etc/profile.d/cis_profile.sh
    owner: root
    group: root
    mode: '0644'
  when: cis_profile_stat.stat.exists
  tags:
    - baseline
    - tmout

- name: Configure default umask
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK'
    line: 'UMASK    {{ system_default_umask }}'
  tags:
    - baseline
    - umask

- name: Install mail handling
  package:
    state: present
    name: '{{ item }}'
  loop:
    - '{{ baseline_mta_packagename }}'
    - '{{ baseline_mail_packagename }}'
  when: baseline_install_mta
  tags:
    - baseline
    - mail

- name: Enable MTA
  systemd_service:
    name: '{{ baseline_mta_servicename }}'
    enabled: true
    state: started
  when: baseline_install_mta
  tags:
    - baseline
    - mail
